/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wansesbank;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils; //check the rs2xml.jar file + i've imported that file (Done) "i used this for the JTable mainly"
import javax.swing.JScrollPane;

/**
 *
 * @author Wans
 */
public class EmployeeFrame extends javax.swing.JFrame {

    private static final String USERNAME = "sql7330374";
    private static final String PASSWORD = "1Tlj6f1nkB";
    private static final String CONN_STRING = "jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7330374";
    String[] empRoles = {"Accountant", "Security & Fraud Specialist", "Trader", "Fund Manager", "Business Technology Specialist"};
    String myEmpRole;

    Employee user = new Employee();

    /**
     * Creates new form EmployeeFrame
     */
    public EmployeeFrame() {
        initComponents();
    }

    public EmployeeFrame(String username, String password) {
        try (
                Connection connection = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
                Statement statement = connection.createStatement();
                ResultSet resultset = statement.executeQuery("SELECT * FROM EMPLOYEE WHERE username='" + username + "' and password='" + password + "'");) 
        {
               
            //jTable1.setModel(DbUtils.resultSetToTableModel(resultset));
            ResultSetMetaData meta = resultset.getMetaData();

            resultset.next();
            user.setEmp_ID(resultset.getInt(1));
            user.setFirstname(resultset.getString(2));
            user.setLastname(resultset.getString(3));
            user.setUsername(resultset.getString(4));
            user.setPassword(resultset.getString(5));
            user.setEmprole(resultset.getInt(6));

            if (user.getEmprole() == 1) {
                myEmpRole = empRoles[0];
            }
            if (user.getEmprole() == 2) {
                myEmpRole = empRoles[1];
            }
            if (user.getEmprole() == 3) {
                myEmpRole = empRoles[2];
            }
            if (user.getEmprole() == 4) {
                myEmpRole = empRoles[3];
            }
            if (user.getEmprole() == 5) {
                myEmpRole = empRoles[4];
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
        //user.setUsername(username);

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainCenterPane = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        CheckInformationPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        customerFirstNameDEL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customerIDFieldDEL = new javax.swing.JTextField();
        employeePasswordDEL = new javax.swing.JPasswordField();
        deleteButton = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        signoutlabel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Panel");
        setMinimumSize(new java.awt.Dimension(630, 725));
        setPreferredSize(new java.awt.Dimension(920, 860));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        MainCenterPane.setLayout(null);

        CheckInformationPanel.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        CheckInformationPanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 650, 510);

        jLayeredPane1.add(CheckInformationPanel);
        CheckInformationPanel.setBounds(10, 20, 680, 530);

        jPanel2.setLayout(null);

        jLabel4.setText("Customer ID :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 40, 80, 16);

        jToggleButton1.setText("DELETE CUSTOMER");
        jPanel2.add(jToggleButton1);
        jToggleButton1.setBounds(220, 500, 140, 32);

        customerFirstNameDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerFirstNameDELActionPerformed(evt);
            }
        });
        jPanel2.add(customerFirstNameDEL);
        customerFirstNameDEL.setBounds(500, 30, 100, 30);

        jLabel5.setText("Customer Firstname  : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(360, 40, 150, 16);

        jLabel6.setText("Employee Password  : ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(180, 120, 130, 16);

        customerIDFieldDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDFieldDELActionPerformed(evt);
            }
        });
        jPanel2.add(customerIDFieldDEL);
        customerIDFieldDEL.setBounds(150, 30, 100, 30);

        employeePasswordDEL.setText("jPasswordField1");
        jPanel2.add(employeePasswordDEL);
        employeePasswordDEL.setBounds(320, 110, 100, 30);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteButton);
        deleteButton.setBounds(260, 190, 73, 32);

        jLayeredPane1.add(jPanel2);
        jPanel2.setBounds(20, 550, 700, 280);

        MainCenterPane.add(jLayeredPane1);
        jLayeredPane1.setBounds(190, 10, 730, 840);

        jPanel1.setLayout(null);

        signoutlabel.setText("Sign out");
        signoutlabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutlabelActionPerformed(evt);
            }
        });
        jPanel1.add(signoutlabel);
        signoutlabel.setBounds(10, 460, 140, 32);

        jLabel3.setText("Employee ID: "+user.getEmp_ID());
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 300, 16);

        jLabel2.setText("Employee Role:"+myEmpRole);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 230, 16);

        jLabel1.setText("Employee Name: "+user.getFirstname());
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 240, 16);

        updatebutton.setText("Update a cutomer");
        jPanel1.add(updatebutton);
        updatebutton.setBounds(10, 190, 140, 32);

        deletebutton.setText("Delete a cutomer");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton);
        deletebutton.setBounds(10, 110, 140, 32);

        addbutton.setText("Add a cutomer");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addbutton);
        addbutton.setBounds(10, 150, 140, 32);

        jButton1.setText("Check Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 230, 140, 32);

        jLayeredPane2.add(jPanel1);
        jPanel1.setBounds(0, 0, 200, 620);

        MainCenterPane.add(jLayeredPane2);
        jLayeredPane2.setBounds(0, 0, 200, 620);

        getContentPane().add(MainCenterPane);
        MainCenterPane.setBounds(0, 0, 930, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signoutlabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutlabelActionPerformed

        this.dispose();
        WansesLogin a = new WansesLogin();
        a.setVisible(true);

    }//GEN-LAST:event_signoutlabelActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             try {
                Connection connection = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
                Statement statement = connection.createStatement();
                ResultSet resultset = statement.executeQuery("SELECT CUST_ID,FIRSTNAME,LASTNAME,USERNAME,MEMBERSHIP,INCOME FROM CUSTOMER");
                //add(new JScrollPane(jTable1));   
            
            ResultSetMetaData meta = resultset.getMetaData();
            jTable1.setModel(DbUtils.resultSetToTableModel(resultset));
            

        } catch (SQLException e) {
            System.out.println(e);
        }
        //user.setUsername(username);

        initComponents();

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void customerFirstNameDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerFirstNameDELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerFirstNameDELActionPerformed

    private void customerIDFieldDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDFieldDELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDFieldDELActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
               try {
                   
                Connection connection = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
                Statement statement = connection.createStatement();
                ResultSet resultset = statement.executeQuery("SELECT CUST_ID,FIRSTNAME CUSTOMER WHERE CUST_ID ="+customerIDFieldDEL+" FIRSTNAME= '"+customerFirstNameDEL+"'");
                  

        } catch (SQLException e) {
            System.out.println(e);
        }
        //user.setUsername(username);

        initComponents();
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeFrame().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CheckInformationPanel;
    private javax.swing.JPanel MainCenterPane;
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField customerFirstNameDEL;
    private javax.swing.JTextField customerIDFieldDEL;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JPasswordField employeePasswordDEL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton signoutlabel;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
