/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wansesbank;

/**
 *
 * @author Wans
 */
public class RegisterForm extends javax.swing.JDialog {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        userlabel = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        incomelabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        checkingbox = new javax.swing.JCheckBox();
        savingbox = new javax.swing.JCheckBox();
        accountlabel = new javax.swing.JLabel();
        registerbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register Form");
        setResizable(false);

        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(110, 40, 190, 24);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(110, 70, 190, 24);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(110, 100, 190, 24);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(140, 160, 160, 24);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(110, 130, 190, 24);

        userlabel.setText("Username:");
        jPanel1.add(userlabel);
        userlabel.setBounds(40, 40, 62, 25);

        passlabel.setText("Password:");
        jPanel1.add(passlabel);
        passlabel.setBounds(40, 70, 61, 25);

        fullname.setText("Full Name:");
        jPanel1.add(fullname);
        fullname.setBounds(40, 100, 70, 25);

        incomelabel.setText("Yearly Income* :");
        jPanel1.add(incomelabel);
        incomelabel.setBounds(40, 190, 91, 25);

        jLabel5.setText("Phone Number:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 160, 87, 25);

        jLabel6.setText("Address:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 130, 51, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not interested.", "Below 5000 SAR", "6000-15000 SAR", "16000-35000 SAR", "35000 SAR and ABOVE" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(140, 190, 160, 26);

        checkingbox.setText("Checking Account");
        jPanel1.add(checkingbox);
        checkingbox.setBounds(140, 230, 140, 20);

        savingbox.setText("Saving Account");
        jPanel1.add(savingbox);
        savingbox.setBounds(140, 250, 140, 20);

        accountlabel.setText("Open a:");
        jPanel1.add(accountlabel);
        accountlabel.setBounds(40, 230, 70, 25);

        registerbutton.setText("Register");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(registerbutton);
        registerbutton.setBounds(40, 290, 110, 32);

        cancelbutton.setText("Cancel");
        jPanel1.add(cancelbutton);
        cancelbutton.setBounds(190, 290, 110, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed

        
    }//GEN-LAST:event_registerbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterForm dialog = new RegisterForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountlabel;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JCheckBox checkingbox;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel incomelabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel passlabel;
    private javax.swing.JButton registerbutton;
    private javax.swing.JCheckBox savingbox;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
