/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wansesbank;

import java.net.URL;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wans
 */
public class SummaryFrame extends javax.swing.JFrame {
    private static  final String USERNAME= "wans";
    private static final String PASSWORD= "123";
    private static final String CONN_STRING= "jdbc:derby://localhost:1527/wanses";
    /**
     * Creates new form SummaryFrame
     */public void initSummary(int Checking_ID,int Saving_ID){
         try {
                Connection connection = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
                Statement statement = connection.createStatement();
                ResultSet resultset = statement.executeQuery("select TRANSACTION_ID, SENDER_NAME, AMOUNT, RECIEVER_NAME, TRANSDATE, PURPOSE FROM TRANSACTS WHERE RECIEVER_ID="+Checking_ID+" OR SENDER_ID="+Checking_ID+" OR RECIEVER_ID="+Saving_ID+" ORDER BY TRANSACTION_ID DESC");
            //ResultSetMetaData meta = resultset.getMetaData();
            String []data= new String[6];
            DefaultTableModel fullmodel = (DefaultTableModel)fullsummary.getModel();
            resultset.next();
            for (int i = 0; i < 20; i++) {
                    data[0]= resultset.getString(1);
                    data[1]= resultset.getString(2);
                    data[2]= String.format("%.2f",resultset.getDouble(3));
                    data[3]= resultset.getString(4);
                    data[4]= resultset.getString(5);
                    data[5]= resultset.getString(6);
                    fullmodel.addRow(data);
                    if(!resultset.next())
                        break;
        }
            
  
        } catch (SQLException e) {
            System.out.println(e);
        }
     }
        public SummaryFrame() {
        
        
        initComponents();
    }
    public SummaryFrame(int Checking_ID, int Saving_ID) {
       

        initComponents();
        initSummary(Checking_ID, Saving_ID);
        URL iconURL = getClass().getResource("/wansesbank/images/appicon.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fullsummary = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 420));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        fullsummary.setBackground(new java.awt.Color(255, 255, 255));
        fullsummary.setForeground(new java.awt.Color(52, 92, 118));
        fullsummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Sender", "Amount", "Reciever", "Date", "Purpose"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fullsummary.setGridColor(new java.awt.Color(238, 241, 244));
        fullsummary.setRowHeight(20);
        fullsummary.setSelectionBackground(new java.awt.Color(75, 112, 136));
        jScrollPane1.setViewportView(fullsummary);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 980, 360);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SummaryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fullsummary;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
